import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "./ContextApi.js";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";
import Loader from "./components/Loader";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <title>JMI Quiz</title>
        </head>
        <body className={poppins.variable}>
          <ClerkLoading>
            <Loader />
          </ClerkLoading>
          <ClerkLoaded>
            <ContextProvider>
              <main>{children}</main>
            </ContextProvider>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
